### ISSUE TITLE
If the setUser function is used in a react hook dependency array, it causes an infinite loop

### ISSUE THREAD

**Issue by cdimitroulas** [baselime/react-rum#3]
Hello there 👋 

I believe that the `setUser` function that is returned from the `useBaselimeRum` hook needs to be wrapped with `useCallback` inside the library as currently it can result in an infinite loop when used inside `useEffect`

You can reproduce this easily with some code like this:
```ts
const { setUser } = useBaselimeRum();

useEffect(() => {
  console.log("in effect");
  setUser('fake-user-id');
}, [setUser])
```

The workaround for now is to ignore the linting warning about adding `setUser` to the dependency array, but it would be nice if we didn't need to have this workaround.

I would be happy to look into opening a PR for this fix!

**Comment by Ankcorn** [comment]
Nice, Thanks so much for raising this! :) Taking a look at the PR now
